apiVersion: v1
kind: LimitRange
metadata: 
  name: task-app-limits
  namespace: task-app

spec:
  limits:
    - type: Container

      default:
        cpu: "200m"
        memory: "128Mi"
      defaultRequest:
        cpu: "100m"
        memory: "64Mi"

        # Hard boundaries -- no container in this namespace can exceed these

      max:
        cpu: "1"
        memory: "512Mi"
      min:
        cpu: "50m"
        memory: "32Mi"

